### Numpy Indexing and Selection

In [1]:
import numpy as np

In [7]:
arr = np.arange(0,11)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [10]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[2:5]

array([2, 3, 4])

In [14]:
arr[0:5] = 100  #brodcasting number

In [15]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6]

In [20]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:] = 99

In [22]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy = arr.copy()

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy[:]=100

In [27]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[0][0]

5

In [32]:
arr_2d[0]

array([ 5, 10, 15])

In [34]:
arr_2d[1][1]

25

In [35]:
arr_2d[2][1]

40

In [36]:
arr_2d[1][2]

30

In [37]:
#we can also do like this
arr_2d[2,1]

40

In [38]:
arr_2d[1,2]

30

In [39]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr_2d[:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [42]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [43]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [44]:
#conditional selection

arr=np.arange(1,11)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
arr<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [49]:
bool_array = arr>=7

In [50]:
bool_array

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [52]:
arr[bool_array]   #showing bool val, 1st method

array([ 7,  8,  9, 10])

In [53]:
arr[arr>=7]       #showing bool val,  2nd method

array([ 7,  8,  9, 10])

In [55]:
arr[arr<=3]

array([1, 2, 3])

In [57]:
arr_2d = np.arange(50).reshape(5,10)

In [58]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])