### Numpy Arrays

##### Numpy arrays essentially comes in one dimensional vectors and 2 dimensional Metrices.

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)   #2-D arrays

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)     #(start,stop,stepsize)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(5)    #1-D 

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5)) #2-D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,5,10) #(start,stop,no of point)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
np.linspace(0,11,50)

array([ 0.        ,  0.2244898 ,  0.44897959,  0.67346939,  0.89795918,
        1.12244898,  1.34693878,  1.57142857,  1.79591837,  2.02040816,
        2.24489796,  2.46938776,  2.69387755,  2.91836735,  3.14285714,
        3.36734694,  3.59183673,  3.81632653,  4.04081633,  4.26530612,
        4.48979592,  4.71428571,  4.93877551,  5.16326531,  5.3877551 ,
        5.6122449 ,  5.83673469,  6.06122449,  6.28571429,  6.51020408,
        6.73469388,  6.95918367,  7.18367347,  7.40816327,  7.63265306,
        7.85714286,  8.08163265,  8.30612245,  8.53061224,  8.75510204,
        8.97959184,  9.20408163,  9.42857143,  9.65306122,  9.87755102,
       10.10204082, 10.32653061, 10.55102041, 10.7755102 , 11.        ])

##### 1-D has one bracket, 2-D has two bracket and 3-D has three bracket. 

In [23]:
#identity metrics

np.eye(4)   #no of r and c are same and dig is 1.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
#random
np.random.rand(5)  #1D (uniform dist from 0 to 1)

array([0.58273091, 0.73967718, 0.54684768, 0.3008446 , 0.46025831])

In [27]:
np.random.rand(4,5) #2D

array([[0.15853296, 0.23425999, 0.84426642, 0.93192386, 0.84166166],
       [0.23026165, 0.69128728, 0.23361683, 0.1232977 , 0.49512168],
       [0.5805898 , 0.79705212, 0.80171185, 0.86569451, 0.61703644],
       [0.74843322, 0.24670087, 0.76136875, 0.12587097, 0.11870223]])

In [28]:
 np.random.randn(7)    #standard normal dist

array([-0.56234149,  0.8110431 , -0.97782717, -0.0849975 ,  0.96101647,
       -0.02847987, -2.68348766])

In [29]:
np.random.randn(3,5)

array([[-0.19848375, -0.94393713,  1.23910274,  0.97583685, -1.58134639],
       [-1.51999394, -0.48502814, -1.70623009,  0.17248115,  0.91603   ],
       [ 1.58849543,  1.22748703,  0.41311554, -0.00425929, -1.31874848]])

In [30]:
#random int
np.random.randint(1,50)  #(low,high,size) #lowest inclusive ,highest exclusive

10

In [31]:
np.random.randint(1,77,12)

array([30, 48, 12, 25, 52,  7,  9, 66, 22, 71, 63, 74])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr = np.random.randint(0,50,10)

In [37]:
ranarr

array([30, 14,  0,  5, 17, 28, 49, 42, 23, 38])

In [38]:
#reshape
arr.reshape(5,5)  #(r,c)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranarr

array([30, 14,  0,  5, 17, 28, 49, 42, 23, 38])

In [40]:
#max
ranarr.max()

49

In [41]:
#min
ranarr.min()

0

In [42]:
#index loc of max
ranarr.argmax()

6

In [43]:
#index loc of min
ranarr.argmin()

2

In [44]:
#shape of vector
arr.shape

(25,)

In [47]:
#datatypes
arr.dtype

dtype('int32')